[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { workspace = true }
eframe = { workspace = true }
encase = { workspace = true }
math = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
