[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.1"
eframe = { workspace = true }
encase = { workspace = true }
math = { workspace = true }

[lints]
workspace = true
